# Generated by preprocess_png.py
myconfig = {
    '/home/shuo/arknight/processed_png/1_3_cropped.png': [
        '/home/shuo/arknight/1.wav',
        '/home/shuo/arknight/2.wav',
        '/home/shuo/arknight/3.wav',
        '/home/shuo/arknight/4.wav',
        '/home/shuo/arknight/5.wav',
        '/home/shuo/arknight/6.wav',
    ],
    '/home/shuo/arknight/processed_png/2_3_cropped.png': [
        '/home/shuo/arknight/1.wav',
        '/home/shuo/arknight/2.wav',
        '/home/shuo/arknight/3.wav',
        '/home/shuo/arknight/4.wav',
        '/home/shuo/arknight/5.wav',
        '/home/shuo/arknight/6.wav',
    ],
}
