#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
import argparse
import importlib.util
from pathlib import Path
from PIL import Image


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "config",
        nargs="?",
        default="config.py",
        help="Path to original config.py",
    )
    parser.add_argument(
        "--out-dir",
        default="processed_png",
        help="Directory for processed PNG files",
    )
    parser.add_argument(
        "--out-config",
        default="processed_config.py",
        help="Output processed config file",
    )
    return parser.parse_args()


def resolve_path(path: str, base_dir: Path) -> Path:
    p = Path(path).expanduser()

    if not p.is_absolute():
        p = base_dir / p

    return p.resolve()


def load_config(config_path: Path) -> dict[Path, list[Path]]:
    config_path = config_path.expanduser().resolve()

    if not config_path.exists():
        raise FileNotFoundError(f"config not found: {config_path}")

    spec = importlib.util.spec_from_file_location("user_config", config_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load config: {config_path}")

    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    data = getattr(module, "myconfig", None)

    if not isinstance(data, dict) or not data:
        raise RuntimeError(
            "config must contain: myconfig = {image_path: [audio_path, ...], ...}"
        )

    base_dir = config_path.parent
    result: dict[Path, list[Path]] = {}

    for img, audios in data.items():
        img_path = resolve_path(str(img), base_dir)

        if isinstance(audios, str):
            audio_list = [audios]
        elif isinstance(audios, list | tuple):
            audio_list = list(audios)
        else:
            print(f"[skip] invalid audio list for image: {img}")
            continue

        resolved_audios = []

        for audio in audio_list:
            audio_path = resolve_path(str(audio), base_dir)
            resolved_audios.append(audio_path)

        result[img_path] = resolved_audios

    return result


def output_path_for_image(out_dir: Path, src: Path, used: set[Path]) -> Path:
    base = src.stem
    candidate = out_dir / f"{base}_cropped.png"

    index = 1
    while candidate in used or candidate.exists():
        candidate = out_dir / f"{base}_{index}_cropped.png"
        index += 1

    used.add(candidate)
    return candidate


def crop_alpha_zero_border(src: Path, dst: Path) -> tuple[int, int, int, int]:
    img = Image.open(src).convert("RGBA")
    bbox = img.getchannel("A").getbbox()

    if bbox is None:
        raise RuntimeError(f"fully transparent image: {src}")

    cropped = img.crop(bbox)

    dst.parent.mkdir(parents=True, exist_ok=True)

    # 不调色、不预乘、不改 Alpha，只裁掉四周完全透明区域。
    cropped.save(dst, format="PNG")

    return bbox


def write_config(path: Path, data: dict[Path, list[Path]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    with open(path, "w", encoding="utf-8") as f:
        f.write("# Generated by preprocess_png.py\n")
        f.write("myconfig = {\n")

        for img, audios in data.items():
            f.write(f"    {str(img)!r}: [\n")

            for audio in audios:
                f.write(f"        {str(audio)!r},\n")

            f.write("    ],\n")

        f.write("}\n")


def main() -> int:
    args = parse_args()

    config_path = Path(args.config).expanduser().resolve()
    base_dir = config_path.parent

    out_dir = Path(args.out_dir).expanduser()
    if not out_dir.is_absolute():
        out_dir = base_dir / out_dir

    out_config = Path(args.out_config).expanduser()
    if not out_config.is_absolute():
        out_config = base_dir / out_config

    config = load_config(config_path)

    new_config: dict[Path, list[Path]] = {}
    used_outputs: set[Path] = set()

    for img, audios in config.items():
        if not img.exists():
            print(f"[skip] image not found: {img}")
            continue

        if img.suffix.lower() != ".png":
            print(f"[skip] not png: {img}")
            continue

        valid_audios = []

        for audio in audios:
            if audio.exists():
                valid_audios.append(audio)
            else:
                print(f"[skip] audio not found: {audio}")

        if not valid_audios:
            print(f"[skip] no valid audio for image: {img}")
            continue

        dst = output_path_for_image(out_dir, img, used_outputs)

        try:
            bbox = crop_alpha_zero_border(img, dst)
        except Exception as e:
            print(f"[fail] {img}: {e}")
            continue

        new_config[dst.resolve()] = [audio.resolve() for audio in valid_audios]

        print(f"[ok] {img} -> {dst}, bbox={bbox}")

    if not new_config:
        print("[fail] no valid image/audio pair")
        return 1

    write_config(out_config, new_config)

    print()
    print(f"written config: {out_config}")
    print(f"processed png dir: {out_dir}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
