# Generated by preprocess_png.py
myconfig = {
    '/home/shuo/arknight/processed_png/1_4_cropped.png': [
        '/home/shuo/arknight/start.wav',
    ],
    '/home/shuo/arknight/processed_png/2_4_cropped.png': [
        '/home/shuo/arknight/start.wav',
    ],
}
